import { id } from "@repo/utils/id";
import {
  mysqlTable,
  mysqlEnum,
  char,
  timestamp,
  varchar,
  int,
  uniqueIndex,
} from "drizzle-orm/mysql-core";

/* ============================================================
 * USERS
 * ============================================================ */

export const Table__User = mysqlTable("user", {
  id: autogeneratedId(),
  name: varchar("name", { length: 255 }).notNull(),
  employeeId: char("employee_id", { length: 12 }).notNull().unique(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  password: varchar("password", { length: 255 }).notNull(),
  phoneNumber: phoneNumberColumn("phone_number"),
  emergencyPhoneNumber: char("emergency_phone_number", { length: 10 }),
  role: roleEnum()
    .$defaultFn(() => "AGENT")
    .notNull(),

  ...metadata("USER"),
});

/* ============================================================
 * BANK
 * ============================================================ */

export const Table__Bank = mysqlTable("bank", {
  id: varchar("id", { length: 255 }).unique().notNull(),
  bankName: varchar("bank_name", { length: 255 }).notNull(),
  tagline: varchar("tagline", { length: 255 }),

  ...metadata("BANK"),
});

/* ============================================================
 * LOAN TYPE
 * ============================================================ */

export const Table__LoanType = mysqlTable("loan_type", {
  id: varchar("id", { length: 255 }).unique().notNull(),
  bankLoanType: varchar("bank_loan_type", { length: 255 }).notNull(),

  ...metadata("LOAN"),
});

/* ============================================================
 * BANK LOAN TYPE
 * ============================================================ */

export const Table__BankLoanDetails = mysqlTable(
  "bank_loan_Details",
  {
    id: autogeneratedId(),
    bankId: varchar("bank_id", { length: 255 })
      .references(() => Table__Bank.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      })
      .notNull(),
    loanTypeId: varchar("loan_type_id", { length: 255 })
      .references(() => Table__LoanType.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      })
      .notNull(),
    applyLink: varchar("apply_link", { length: 255 })
      .notNull()
      .$defaultFn(() => "https://example.com"),
    returnOnInvest: int("return_on_invest").notNull(),
    processingTimeInDays: int("processing_time_in_days").notNull(),
    maxTenureInMonth: int("max_tenure_in_month").notNull(),

    ...metadata("BLOA"),
  },
  (t) => [uniqueIndex("bank_loan_unique").on(t.bankId, t.loanTypeId)],
);

/* ============================================================
 * BENEFITS
 * ============================================================ */

export const Table__Benefits = mysqlTable("benefits", {
  id: autogeneratedId(),
  title: varchar("title", { length: 255 }).notNull(),
  description: varchar("description", { length: 255 }).notNull(),
  icon: iconEnum().notNull(),

  ...metadata("BNFT"),
});

/* ============================================================
 * LOAN BENEFITS
 * ============================================================ */

export const Table__LoanBenefits = mysqlTable("loan_benefits", {
  benefitId: foreignId("benefit_id")
    .references(() => Table__Benefits.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),
  bankLoanId: foreignId("bank_loan_id")
    .references(() => Table__BankLoanDetails.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    })
    .notNull(),

  ...metadata("LBNF"),
});

/* ============================================================
 * TYPES, ENUMS & HELPERS
 *
 * Keep these at the bottom.
 * ============================================================ */

/* ============================================================
 * TABLE IDENTIFIER TOKEN
 * ============================================================ */

export type TableIdentifierToken =
  "USER" | "BANK" | "LOAN" | "BLOA" | "BNFT" | "LBNF";

/* ============================================================
 * ROLE
 * ============================================================ */

export function ROLE() {
  return ["ADMIN", "AGENT"] as const;
}

export function roleEnum(columnName = "role") {
  return mysqlEnum(columnName, ROLE());
}

/* ============================================================
 * BENEFIT ICON
 * ============================================================ */

export function ICON() {
  return [
    "ShieldCheck",
    "TrendingUp",
    "CalendarDays",
    "BadgeCheck",
    "Clock",
  ] as const;
}

export function iconEnum(columnName = "icon") {
  return mysqlEnum(columnName, ICON());
}

/* ============================================================
 * CREATED AT
 * ============================================================ */

export function createdAt(columnName = "created_at") {
  return timestamp(columnName, {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .notNull();
}

/* ============================================================
 * UPDATED AT
 * ============================================================ */

export function updatedAt(columnName = "updated_at") {
  return timestamp(columnName, {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date())
    .notNull();
}

/* ============================================================
 * METADATA
 * ============================================================ */

export function metadata(token: TableIdentifierToken) {
  return {
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    tableIdentifierToken: tokenColumn(token),
  };
}

/* ============================================================
 * TABLE IDENTIFIER TOKEN COLUMN
 * ============================================================ */

export function tableIdentifierToken(columnName = "table_identifier_token") {
  return mysqlEnum(columnName, [
    "USER",
    "BANK",
    "BLOA",
    "BNFT",
    "LBNF",
    "LOAN",
  ] as [TableIdentifierToken, ...TableIdentifierToken[]]);
}

export function tokenColumn(token: TableIdentifierToken) {
  return tableIdentifierToken().notNull().default(token);
}

/* ============================================================
 * ID HELPERS
 * ============================================================ */

/**
 * Generates a 10-character uppercase ID.
 *
 * Example:
 *   A81F3C921
 */
export function autogeneratedId() {
  return char("id", {
    length: 10,
  })
    .primaryKey()
    .notNull()
    .$defaultFn(() =>
      id(),
    );
}

/**
 * Foreign keys use the exact same format as autogeneratedId().
 */
export function foreignId(columnName: string) {
  return char(columnName, {
    length: 10,
  });
}

/* ============================================================
 * COMMON COLUMN HELPERS
 * ============================================================ */

export function phoneNumberColumn(columnName = "phone_number") {
  return char(columnName, {
    length: 10,
  }).notNull();
}

/* ============================================================
 * TABLE MAP
 * ============================================================ */

export const tableMap = {
  USER: "user",
  BANK: "bank",
  BLOA: "bank_loan_Details",
  BNFT: "benefits",
  LBNF: "loan_benefits",
  LOAN: "loan_type",
} as const;

/* ============================================================
 * TABLE IDENTIFICATION
 * ============================================================ */

export function identifyTable(token: keyof typeof tableMap) {
  return tableMap[token];
}
