name: sr-loan

networks:
  sr-loan-prod-local:
    driver: bridge

services:
  dashboard:
    container_name: sr-loan-prod-local-live
    # pull_policy: "always"
    image: "nirvikpurkait/sr-loan-dashboard"
    build:
      context: ../../
      dockerfile: apps/dashboard/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        DASHBOARD_APP_HOST: ${DASHBOARD_APP_HOST}
        VITE_DASHBOARD_APP_HOST: ${VITE_DASHBOARD_APP_HOST}
        TOKEN_SECRET: ${TOKEN_SECRET}
        SALT_ROUND: ${SALT_ROUND}
        TURBO_TOKEN: ${TURBO_TOKEN}
        TURBO_TEAM: ${TURBO_TEAM}
    env_file:
      - ../../.env.production
    ports:
      - 18532:3000
    networks:
      - sr-loan-prod-local
