name: sr-loan

networks:
  sr-laon-prod-local:
    driver: bridge

services:
  dashboard:
    container_name: sr-laon-dashboard
    image: "sr-laon-dashboard"
    build:
      context: ../../
      dockerfile: apps/dashboard/Dockerfile
      args:
        VITE_DASHBOARD_APP_HOST: ${VITE_DASHBOARD_APP_HOST}
        DATABASE_URL: ${DATABASE_URL}
        TOKEN_SECRET: ${TOKEN_SECRET}
        SALT_ROUND: ${SALT_ROUND}
        DASHBOARD_APP_HOST: ${DASHBOARD_APP_HOST}
    ports:
      - 19100:3000
    env_file:
      - ../../.env.production
    networks:
      - sr-laon-prod-local
