name: sr-loan-prod-local

networks:
  sr-loan-prod-local:
    driver: bridge

services:
  sr-loan-prod-local-phpmyadmin:
    container_name: sr-loan-prod-local-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "17120:80"
    environment:
      PMA_HOST: sr-loan-prod-local-database
      PMA_PORT: 3306
    networks:
      - sr-loan-prod-local

  sr-loan-prod-local-database:
    container_name: sr-loan-prod-local-database
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 12189:3306
    networks:
      - sr-loan-prod-local
    volumes:
      - database:/var/lib/mysql

  sr-loan-prod-local-nginx:
    container_name: sr-loan-prod-local-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sr-loan-prod-local
    volumes:
      - ../nginx.prod.local.secure.conf:/etc/nginx/nginx.conf:ro
      - ../localhost-cert.pem:/etc/nginx/certs/localhost-cert.pem:ro
      - ../localhost-key.pem:/etc/nginx/certs/localhost-key.pem:ro

  sr-loan-prod-local-campus:
    container_name: sr-loan-prod-local-campus
    image: "nirvikpurkait/campus-app"
    env_file:
      - ../.env.production.local
    ports:
      - 19100:3000
    networks:
      - sr-loan-prod-local

  sr-loan-prod-local-live:
    container_name: sr-loan-prod-local-live
    image: "nirvikpurkait/live-app"
    env_file:
      - ../.env.production.local
    ports:
      - 18532:3000
    networks:
      - sr-loan-prod-local

  sr-loan-prod-local-socket:
    container_name: sr-loan-prod-local-socket
    image: "nirvikpurkait/socket-app"
    env_file:
      - ../.env.production.local
    ports:
      - 14814:3000
    networks:
      - sr-loan-prod-local

  sr-loan-prod-local-storage:
    container_name: sr-loan-prod-local-storage
    image: "nirvikpurkait/storage-app"
    env_file:
      - ../.env.production.local
    ports:
      - 19607:3000
    networks:
      - sr-loan-prod-local

volumes:
  database:
